name: get-package-names
description: Gets the packages inside of a monorepo with optional filters

branding:
  icon: package
  color: gray-dark

inputs:
  script-name:
    description: The name of a "package.json" script. If specified, only monorepo packages that contain a script with the specified name will be returned.
    required: false
    default: ""

outputs:
  package-names:
    description: 'The names of the directories that were found in the monorepo "packages" directory. For example: ["foo", "bar"]'

runs:
  using: node20
  main: dist/main.js
